2019-05-21 13:09:40,270 ERROR 12735 [-/127.0.0.1/-/11ms GET /api/member] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'sorter' in 'order clause'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: SELECT * FROM `pme_member` ORDER BY `sorter` DESC
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'sorter' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `pme_member` ORDER BY `sorter` DESC"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 12735
hostname: xiaohuangyudeMacBook-Pro.local

2019-05-21 13:11:43,046 ERROR 12735 [-/127.0.0.1/-/6ms GET /api/member] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'sorter' in 'order clause'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: SELECT * FROM `pme_member` ORDER BY `sorter` DESC
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'sorter' in 'order clause'"
sqlState: "42S22"
index: 0
sql: "SELECT * FROM `pme_member` ORDER BY `sorter` DESC"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 12735
hostname: xiaohuangyudeMacBook-Pro.local

2019-05-21 15:16:07,005 ERROR 12735 [-/127.0.0.1/-/36ms POST /api/platform] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'phone' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: INSERT INTO `pme_platform`(`phone`, `password`, `password2`, `status`) VALUES('15802817170', '111111', '111111', true)
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'phone' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `pme_platform`(`phone`, `password`, `password2`, `status`) VALUES('15802817170', '111111', '111111', true)"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 12735
hostname: xiaohuangyudeMacBook-Pro.local

2019-05-21 15:19:51,410 ERROR 12865 [-/127.0.0.1/-/26ms POST /api/platform] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'phone' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: INSERT INTO `pme_platform`(`phone`, `password`, `password2`, `status`) VALUES('15802817170', '111111', '111111', true)
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'phone' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `pme_platform`(`phone`, `password`, `password2`, `status`) VALUES('15802817170', '111111', '111111', true)"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 12865
hostname: xiaohuangyudeMacBook-Pro.local

2019-05-21 15:20:28,544 ERROR 12865 [-/127.0.0.1/-/3ms POST /api/platform] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'phone' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: INSERT INTO `pme_platform`(`phone`, `password`, `password2`, `status`) VALUES('15802817170', '111111', '111111', true)
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'phone' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `pme_platform`(`phone`, `password`, `password2`, `status`) VALUES('15802817170', '111111', '111111', true)"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 12865
hostname: xiaohuangyudeMacBook-Pro.local

