2019-04-05 13:44:28,825 ERROR 6720 [-/::1/-/10ms DELETE /api/friendlink/1] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'where' in 'where clause'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: DELETE FROM `pme_friendlink` WHERE `where` = `id` = '1'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'where' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "DELETE FROM `pme_friendlink` WHERE `where` = `id` = '1'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 6720
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-05 13:44:42,349 ERROR 6720 [-/::1/-/1ms DELETE /api/friendlink/1] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'where' in 'where clause'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: DELETE FROM `pme_friendlink` WHERE `where` = `id` = '1'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'where' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "DELETE FROM `pme_friendlink` WHERE `where` = `id` = '1'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 6720
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-05 13:45:10,381 ERROR 6720 [-/::1/-/2ms DELETE /api/friendlink/2] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'where' in 'where clause'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: DELETE FROM `pme_friendlink` WHERE `where` = `id` = '2'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'where' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "DELETE FROM `pme_friendlink` WHERE `where` = `id` = '2'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 6720
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-05 13:45:36,319 ERROR 6720 [-/::1/-/2ms DELETE /api/friendlink/2] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'where' in 'where clause'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: DELETE FROM `pme_friendlink` WHERE `where` = `id` = '2'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'where' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "DELETE FROM `pme_friendlink` WHERE `where` = `id` = '2'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 6720
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-05 13:47:20,260 ERROR 6797 [-/::1/-/12ms DELETE /api/friendlink/2] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'where' in 'where clause'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: DELETE FROM `pme_friendlink` WHERE `where` = `id` = '2'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'where' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "DELETE FROM `pme_friendlink` WHERE `where` = `id` = '2'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 6797
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-05 13:47:57,323 ERROR 6802 [-/::1/-/14ms DELETE /api/friendlink/3] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'where' in 'where clause'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: DELETE FROM `pme_friendlink` WHERE `where` = `id` = '3'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'where' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "DELETE FROM `pme_friendlink` WHERE `where` = `id` = '3'"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 6802
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-05 14:57:13,239 WARN 6807 [-/::1/-/6ms PUT /api/friendlink/1] nodejs.UnprocessableEntityError: Validation Failed
    at Object.throw (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/koa/lib/context.js:97:11)
    at Object.validate (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/egg-validate/app/extend/context.js:14:17)
    at FriendlinkController.update (/Users/xiaohuangyu/work/egg-ams/admin/app/controller/admin/api/friendlink.js:32:18)
    at Object.callFn (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/@eggjs/router/lib/router.js:190:18
message: "Validation Failed"
code: "invalid_param"
errors: [{"message":"should be a string","code":"invalid","field":"id"}]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 6807
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-05 14:58:48,414 WARN 6879 [-/::1/-/30ms PUT /api/friendlink/5] nodejs.UnprocessableEntityError: Validation Failed
    at Object.throw (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/koa/lib/context.js:97:11)
    at Object.validate (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/egg-validate/app/extend/context.js:14:17)
    at FriendlinkController.update (/Users/xiaohuangyu/work/egg-ams/admin/app/controller/admin/api/friendlink.js:32:13)
    at Object.callFn (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/koa-compose/index.js:45:18)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/@eggjs/router/lib/router.js:190:18
message: "Validation Failed"
code: "invalid_param"
errors: [{"message":"should be a string","code":"invalid","field":"id"}]
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 6879
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-05 15:03:21,275 ERROR 6891 [-/::1/-/42ms PUT /api/friendlink/1] nodejs.ReferenceError: rres is not defined
    at FriendlinkController.update (/Users/xiaohuangyu/work/egg-ams/admin/app/controller/admin/api/friendlink.js:36:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 6891
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-05 15:04:02,560 ERROR 6891 [-/::1/-/5ms PUT /api/friendlink/1] nodejs.ReferenceError: rres is not defined
    at FriendlinkController.update (/Users/xiaohuangyu/work/egg-ams/admin/app/controller/admin/api/friendlink.js:36:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 6891
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-05 15:30:18,342 ERROR 7350 [-/192.168.71.43/-/5ms PUT /api/friendlink/1] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'use' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: UPDATE `pme_friendlink` SET `name` = '百度3', `url` = 'baidu.com', `use` = true, `sorter` = 50, `img` = 'http://localhost:7002/public/upload/images/fea702238465693eb020cb853ecd37b7.png' WHERE `id` = 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'use' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `pme_friendlink` SET `name` = '百度3', `url` = 'baidu.com', `use` = true, `sorter` = 50, `img` = 'http://localhost:7002/public/upload/images/fea702238465693eb020cb853ecd37b7.png' WHERE `id` = 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 7350
hostname: xiaohuangyudeMacBook-Pro.local

2019-04-05 15:30:37,452 ERROR 7350 [-/192.168.71.43/-/2ms PUT /api/slider/1] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'field list'
    at Query.Sequence._packetToError (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    --------------------
    at Pool.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/client.js:34:20)
    at RDSClient.proto.query (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:65:19)
    at /Users/xiaohuangyu/work/egg-ams/admin/node_modules/co/index.js:54:5
    sql: UPDATE `pme_slider` SET `name` = '百度先', `url` = 'baidu.com', `use` = true, `sorter` = 50, `img` = '' WHERE `id` = 1
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'field list'"
sqlState: "42S22"
index: 0
sql: "UPDATE `pme_slider` SET `name` = '百度先', `url` = 'baidu.com', `use` = true, `sorter` = 50, `img` = '' WHERE `id` = 1"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 7350
hostname: xiaohuangyudeMacBook-Pro.local

